services:
  # Apache and PHP service
  web:
    image: php:7.4-apache
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./snake:/var/www/html
    networks:
      - app-network

  # MySQL service
  mysql:
    image: mysql:latest
    networks:
      - app-network
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 32-117-kill3rb33
      MYSQL_DATABASE: the_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 32-117-kill3rb33
    volumes: 
      - ./snake/init.sql:/docker-entrypoint-initdb.d/init.sql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-network
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 32-117-kill3rb33
    depends_on:
      - mysql

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - web

# Define networks
networks:
  app-network:
    driver: bridge