CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    profile_pic VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    m_id VARCHAR(255) NOT NULL,
    m_user VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    timestamp VARCHAR(255)
);
